INSERT IGNORE INTO permissions (code, name, module) VALUES
('dashboard.view', 'Ver dashboard', 'dashboard'),
('setup.manage', 'Completar configuración inicial', 'setup'),
('users.view', 'Ver usuarios', 'users'),
('users.manage', 'Administrar usuarios', 'users'),
('roles.manage', 'Administrar roles y permisos', 'users'),
('masters.manage', 'Administrar maestros agrícolas', 'masters'),
('costs.view', 'Ver costos', 'costs'),
('costs.manage', 'Registrar y corregir costos', 'costs'),
('labor.manage', 'Administrar mano de obra', 'labor'),
('inventory.view', 'Ver bodega', 'inventory'),
('inventory.manage', 'Administrar movimientos de bodega', 'inventory'),
('reports.view', 'Ver informes', 'reports'),
('reports.export', 'Exportar informes', 'reports'),
('procurement.receive', 'Registrar recepción de compras', 'procurement'),
('warehouse.view', 'Ver bodegas', 'warehouse'),
('warehouse.create', 'Crear bodegas y ubicaciones', 'warehouse'),
('warehouse.update', 'Actualizar bodegas y ubicaciones', 'warehouse'),
('lot.create', 'Crear lotes', 'inventory'),
('transfer.create', 'Crear transferencias', 'inventory'),
('transfer.approve', 'Aprobar transferencias', 'inventory'),
('requests.view', 'Ver solicitudes internas', 'requests'),
('requests.create', 'Crear solicitudes internas', 'requests'),
('requests.approve', 'Aprobar solicitudes internas', 'requests'),
('requests.fulfill', 'Atender solicitudes internas', 'requests'),
('notifications.view', 'Ver notificaciones', 'notifications'),
('notifications.update', 'Actualizar notificaciones', 'notifications'),
('tasks.view', 'Ver tareas', 'tasks'),
('tasks.create', 'Crear tareas', 'tasks'),
('tasks.update', 'Actualizar tareas', 'tasks'),
('calendar.view', 'Ver calendario', 'calendar'),
('calendar.create', 'Crear eventos de calendario', 'calendar'),
('documents.view', 'Ver documentos', 'documents'),
('documents.create', 'Crear documentos', 'documents'),
('attachments.create', 'Adjuntar archivos', 'documents'),
('api_tokens.manage', 'Administrar tokens API', 'api'),
('masters.view', 'Ver maestros agrícolas', 'masters'),
('masters.create', 'Crear maestros agrícolas', 'masters'),
('production.view', 'Ver producción', 'production'),
('production.create', 'Registrar producción', 'production'),
('procurement.view', 'Ver compras', 'procurement'),
('procurement.create', 'Crear compras', 'procurement'),
('budgets.view', 'Ver presupuestos', 'budgets'),
('budgets.create', 'Crear presupuestos', 'budgets'),
('machinery.view', 'Ver maquinaria', 'machinery'),
('machinery.create', 'Crear maquinaria', 'machinery'),
('costs.create', 'Registrar costos', 'costs'),
('inventory.create', 'Crear insumos y movimientos', 'inventory'),
('labor.view', 'Ver mano de obra', 'labor'),
('labor.create', 'Registrar mano de obra', 'labor');
