INSERT INTO system_catalog_values (catalog_id, company_id, code, label, sort_order)
SELECT catalogs.id, NULL, values_table.code, values_table.label, values_table.sort_order
FROM system_catalogs catalogs
JOIN (
    SELECT 'RECORD_STATUS' AS catalog_code, 'DRAFT' AS code, 'Borrador' AS label, 10 AS sort_order
    UNION ALL SELECT 'RECORD_STATUS', 'POSTED', 'Registrado', 20
    UNION ALL SELECT 'RECORD_STATUS', 'VOID', 'Anulado', 30
    UNION ALL SELECT 'COST_CATEGORY', 'ADMINISTRACION', 'Administración', 10
    UNION ALL SELECT 'COST_CATEGORY', 'MANO_DE_OBRA', 'Mano de obra', 20
    UNION ALL SELECT 'COST_CATEGORY', 'INVERSION', 'Inversión', 30
    UNION ALL SELECT 'COST_CATEGORY', 'SERVICIOS_GASTOS', 'Servicios y gastos', 40
    UNION ALL SELECT 'COST_CATEGORY', 'BODEGA', 'Bodega', 50
    UNION ALL SELECT 'INVENTORY_CATEGORY', 'INSUMO', 'Insumo', 10
    UNION ALL SELECT 'INVENTORY_CATEGORY', 'FERRETERIA', 'Ferretería', 20
    UNION ALL SELECT 'INVENTORY_CATEGORY', 'MAQUINARIA', 'Maquinaria', 30
    UNION ALL SELECT 'INVENTORY_CATEGORY', 'HERRAMIENTA', 'Herramienta', 40
    UNION ALL SELECT 'INVENTORY_CATEGORY', 'OTRO', 'Otro', 50
    UNION ALL SELECT 'INVENTORY_MOVEMENT_TYPE', 'IN', 'Entrada', 10
    UNION ALL SELECT 'INVENTORY_MOVEMENT_TYPE', 'OUT', 'Salida', 20
    UNION ALL SELECT 'INVENTORY_MOVEMENT_TYPE', 'ADJUSTMENT', 'Ajuste', 30
    UNION ALL SELECT 'WORKER_TYPE', 'PERMANENTE', 'Permanente', 10
    UNION ALL SELECT 'WORKER_TYPE', 'TEMPORAL', 'Temporal', 20
    UNION ALL SELECT 'WORKER_TYPE', 'CONTRATISTA', 'Contratista', 30
    UNION ALL SELECT 'MAINTENANCE_TYPE', 'PREVENTIVE', 'Preventiva', 10
    UNION ALL SELECT 'MAINTENANCE_TYPE', 'CORRECTIVE', 'Correctiva', 20
    UNION ALL SELECT 'MACHINERY_TYPE', 'TRACTOR', 'Tractor', 10
    UNION ALL SELECT 'MACHINERY_TYPE', 'IMPLEMENT', 'Implemento', 20
    UNION ALL SELECT 'LABOR_TYPE', 'GENERAL', 'Labor general', 10
    UNION ALL SELECT 'LABOR_TYPE', 'HARVEST', 'Cosecha', 20
    UNION ALL SELECT 'PRODUCTION_QUALITY', 'PREMIUM', 'Premium', 10
    UNION ALL SELECT 'PRODUCTION_QUALITY', 'STANDARD', 'Estándar', 20
    UNION ALL SELECT 'PURCHASE_ORDER_STATUS', 'DRAFT', 'Borrador', 10
    UNION ALL SELECT 'PURCHASE_ORDER_STATUS', 'SENT', 'Enviada', 20
    UNION ALL SELECT 'PURCHASE_ORDER_STATUS', 'PARTIAL', 'Parcial', 30
    UNION ALL SELECT 'PURCHASE_ORDER_STATUS', 'RECEIVED', 'Recibida', 40
    UNION ALL SELECT 'PURCHASE_ORDER_STATUS', 'CANCELLED', 'Cancelada', 50
    UNION ALL SELECT 'REQUEST_STATUS', 'DRAFT', 'Borrador', 10
    UNION ALL SELECT 'REQUEST_STATUS', 'REQUESTED', 'Solicitada', 20
    UNION ALL SELECT 'REQUEST_STATUS', 'APPROVED', 'Aprobada', 30
    UNION ALL SELECT 'REQUEST_STATUS', 'FULFILLED', 'Atendida', 40
    UNION ALL SELECT 'REQUEST_STATUS', 'REJECTED', 'Rechazada', 50
    UNION ALL SELECT 'DOCUMENT_STATUS', 'DRAFT', 'Borrador', 10
    UNION ALL SELECT 'DOCUMENT_STATUS', 'VALID', 'Válido', 20
    UNION ALL SELECT 'DOCUMENT_STATUS', 'VOID', 'Anulado', 30
    UNION ALL SELECT 'MACHINERY_STATUS', 'ACTIVE', 'Activa', 10
    UNION ALL SELECT 'MACHINERY_STATUS', 'MAINTENANCE', 'En mantención', 20
    UNION ALL SELECT 'MACHINERY_STATUS', 'INACTIVE', 'Inactiva', 30
    UNION ALL SELECT 'BACKUP_STATUS', 'STARTED', 'Iniciado', 10
    UNION ALL SELECT 'BACKUP_STATUS', 'COMPLETED', 'Completado', 20
    UNION ALL SELECT 'BACKUP_STATUS', 'FAILED', 'Fallido', 30
) values_table ON values_table.catalog_code = catalogs.code
WHERE (catalogs.scope = 'SYSTEM' OR catalogs.scope = 'COMPANY')
  AND NOT EXISTS (
      SELECT 1 FROM system_catalog_values existing
      WHERE existing.catalog_id = catalogs.id AND existing.company_id IS NULL AND existing.code = values_table.code
  );
