<?php

declare(strict_types=1);

return [
    'executive' => [
        'title' => 'Dashboard Ejecutivo',
        'description' => 'Rentabilidad, producción y productividad para la gerencia agrícola.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/executive',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'season'],
    ],
    'production' => [
        'title' => 'Producción',
        'description' => 'Volumen, rendimiento y productividad del cultivo.',
        'icon' => 'plant',
        'permission' => 'reports.view',
        'route' => '/reports/production',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'crop', 'process', 'variety'],
    ],
    'costs' => [
        'title' => 'Costos',
        'description' => 'Estructura de costos, centros de gasto e indicadores financieros.',
        'icon' => 'dollar',
        'permission' => 'reports.view',
        'route' => '/reports/costs',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'cost_center', 'category', 'type', 'supplier'],
    ],
    'profitability' => [
        'title' => 'Rentabilidad',
        'description' => 'Margen financiero y eficiencia de recursos.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/profitability',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'season', 'farm', 'cost_center', 'crop'],
    ],
    'labor' => [
        'title' => 'Mano de obra',
        'description' => 'Costos, jornadas y productividad laboral.',
        'icon' => 'users',
        'permission' => 'reports.view',
        'route' => '/reports/labor',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'worker', 'crew', 'supervisor', 'process'],
    ],
    'inventory' => [
        'title' => 'Inventario',
        'description' => 'Stock, rotación y alertas de reposición.',
        'icon' => 'boxes',
        'permission' => 'reports.view',
        'route' => '/reports/inventory',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'warehouse', 'category', 'product', 'family'],
    ],
    'procurement' => [
        'title' => 'Compras',
        'description' => 'Estado de órdenes, recepciones y proveedores.',
        'icon' => 'cart',
        'permission' => 'reports.view',
        'route' => '/reports/procurement',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'supplier', 'farm', 'cost_center', 'category'],
    ],
    'finance' => [
        'title' => 'Finanzas',
        'description' => 'Ingresos, gastos, flujo de caja y ejecución presupuestaria.',
        'icon' => 'dollar',
        'permission' => 'reports.view',
        'route' => '/reports/finance',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'season', 'cost_center'],
    ],
    'budgets' => [
        'title' => 'Presupuestos',
        'description' => 'Planificación y ejecución de presupuestos.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/budgets',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'season', 'cost_center'],
    ],
    'machinery' => [
        'title' => 'Maquinaria',
        'description' => 'Uso de equipos, horas de trabajo y costos operativos.',
        'icon' => 'wrench',
        'permission' => 'reports.view',
        'route' => '/reports/machinery',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'machine_type', 'cost_center'],
    ],
    'productivity' => [
        'title' => 'Productividad',
        'description' => 'Indicadores clave de eficiencia productiva.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/productivity',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'block', 'crop', 'process'],
    ],
    'comparatives' => [
        'title' => 'Comparativos',
        'description' => 'Comparación entre periodos, temporadas y segmentos.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/comparatives',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'season', 'cost_center'],
    ],
    'trends' => [
        'title' => 'Tendencias',
        'description' => 'Evolución de costos, producción y mano de obra.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/trends',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'cost_center', 'process'],
    ],
    'kpis' => [
        'title' => 'KPIs',
        'description' => 'Indicadores clave de desempeño corporativo.',
        'icon' => 'chart',
        'permission' => 'reports.view',
        'route' => '/reports/kpis',
        'filters' => ['year', 'month', 'week', 'day', 'date_range', 'farm', 'season', 'cost_center'],
    ],
];
