<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Maestros agrícolas | Sistema de Gestión Agrícola PCCURICO</title>
    <link rel="stylesheet" href="assets/css/app.css">
</head>
<body class="admin-page">
    <main class="admin-shell">
        <?php require dirname(__DIR__) . '/Views/partials/module-navigation.php'; ?>
        <section class="module-content">
        <header class="admin-header"><div><p class="eyebrow">Administración de la agrícola</p><h1>Fundos, especies y temporadas</h1><p class="setup-copy">Registra aquí la información que usarás en costos, inventario y producción.</p></div><a class="secondary-link" href="/">Volver al dashboard</a></header>
        <?php if ($error): ?><div class="setup-error"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
        <?php if ($success): ?><div class="setup-success"><?= htmlspecialchars($success, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
        <section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Fundos registrados</h2><p>Consulta los fundos que ya has ingresado.</p></header><div class="table-scroll"><table class="admin-table"><thead><tr><th>Fundo</th><th>Código</th><th>Hectáreas</th><th>Ubicación</th><th>Cuarteles</th></tr></thead><tbody><?php foreach ($farms as $farm): ?><tr><td><?= htmlspecialchars($farm['name']) ?></td><td><?= htmlspecialchars($farm['code']) ?></td><td><?= number_format((float) $farm['hectares'], 2, ',', '.') ?></td><td><?= htmlspecialchars($farm['location'] ?: 'Sin ubicación') ?></td><td><?= count(array_filter($blocks, fn ($block) => (int) $block['farm_id'] === (int) $farm['id'])) ?></td></tr><?php endforeach; ?></tbody></table></div><div class="inline-form"><h3>Agregar un fundo</h3><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="create_master"><input type="hidden" name="type" value="farm"><label>Nombre del fundo<input name="name" required></label><label>Código<input name="code" required></label><label>Hectáreas<input name="hectares" type="number" min="0" step="0.01"></label><label>Ubicación<input name="location"></label><button class="small-button" type="submit">Agregar fundo</button></form></div></article>
        <article class="admin-panel"><header class="panel-header"><h2>Nuevo cuartel</h2><p>Asigna especie y superficie productiva</p></header><form method="post" class="admin-form"><input type="hidden" name="action" value="create_master"><input type="hidden" name="type" value="block"><label>Fundo<select name="farm_id" required><?php foreach ($farms as $farm): ?><option value="<?= (int) $farm['id'] ?>"><?= htmlspecialchars($farm['name']) ?></option><?php endforeach; ?></select></label><label>Código<input name="code" required placeholder="5A"></label><label>Nombre<input name="name" required placeholder="Cuartel 5A"></label><label>Especie<select name="species_id"><option value="">Sin asignar</option><?php foreach ($species as $item): ?><option value="<?= (int) $item['id'] ?>"><?= htmlspecialchars($item['name'] . ($item['variety'] ? ' · ' . $item['variety'] : '')) ?></option><?php endforeach; ?></select></label><label>Hectáreas<input name="hectares" type="number" min="0" step="0.01"></label><label>Año de plantación<input name="planting_year" type="number" min="1900" max="2100"></label><button class="primary-button" type="submit">Crear cuartel</button></form></article></section>
        <section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Especies y variedades</h2><p>Catálogo productivo para la trazabilidad</p></header><div class="table-scroll"><table class="admin-table"><thead><tr><th>Especie</th><th>Variedad</th><th>Estado</th></tr></thead><tbody><?php foreach ($species as $item): ?><tr><td><b><?= htmlspecialchars($item['name']) ?></b></td><td><?= htmlspecialchars($item['variety'] ?: 'General') ?></td><td><span class="status-pill status-active">Activo</span></td></tr><?php endforeach; ?></tbody></table></div><div class="inline-form"><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action" value="create_master"><input type="hidden" name="type" value="species"><input name="name" placeholder="Especie" required><input name="variety" placeholder="Variedad"><button class="small-button" type="submit">Agregar especie</button></form></div></article>
        <article class="admin-panel"><header class="panel-header"><h2>Temporadas activas</h2><p>Períodos usados en reportes y costos</p></header><div class="role-list"><?php foreach ($seasons as $season): ?><div class="role-row"><div><b><?= htmlspecialchars($season['name']) ?></b><small><?= htmlspecialchars($season['starts_on']) ?> al <?= htmlspecialchars($season['ends_on']) ?></small></div><span class="status-pill status-active">Activa</span></div><?php endforeach; ?></div><form method="post" class="admin-form"><input type="hidden" name="action" value="create_master"><input type="hidden" name="type" value="season"><label>Nombre<input name="name" required placeholder="2026-2027"></label><label>Inicio<input type="date" name="starts_on" required></label><label>Término<input type="date" name="ends_on" required></label><button class="small-button" type="submit">Agregar temporada</button></form></article></section>
        <section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Centros de costo</h2><p>Clasificación para los informes financieros</p></header><div class="role-list"><?php foreach ($cost_centers as $center): ?><div class="role-row"><div><b><?= htmlspecialchars($center['name']) ?></b><small><?= htmlspecialchars($center['code']) ?></small></div><span><?= htmlspecialchars($center['category']) ?></span></div><?php endforeach; ?></div></article><article class="admin-panel"><header class="panel-header"><h2>Nuevo centro de costo</h2><p>Agrega una clasificación contable</p></header><form method="post" class="admin-form"><input type="hidden" name="action" value="create_master"><input type="hidden" name="type" value="cost_center"><label>Código<input name="code" required placeholder="ADM-001"></label><label>Nombre<input name="name" required placeholder="Administración general"></label><label>Categoría<select name="category" required><option value="ADMINISTRACION">Administración</option><option value="MANO_DE_OBRA">Mano de obra</option><option value="INVERSION">Inversión</option><option value="SERVICIOS_GASTOS">Servicios y gastos</option><option value="BODEGA">Bodega</option></select></label><button class="small-button" type="submit">Agregar centro</button></form></article></section>
        </section>
    </main>
</body>
</html>
