<?php
$warehouses = $warehouses ?? [];
$locations = $locations ?? [];
$lots = $lots ?? [];
$transfers = $transfers ?? [];
$items = $items ?? [];
$farms = $farms ?? [];
$error = $error ?? null;
$success = $success ?? null;
$csrf = htmlspecialchars(csrf_token(), ENT_QUOTES, 'UTF-8');
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bodegas | CampoSur</title><link rel="stylesheet" href="/assets/css/app.css"></head><body class="admin-page"><main class="admin-shell">
<?php require dirname(__DIR__) . '/Views/partials/module-navigation.php'; ?>
<header class="admin-header"><div><p class="eyebrow">Inventario</p><h1>Bodegas, ubicaciones y lotes</h1><p class="setup-copy">Administra existencias por bodega y controla transferencias internas.</p></div><a class="secondary-link" href="?module=inventory">Volver a inventario</a></header>
<?php if ($error): ?><div class="setup-error"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><?php if ($success): ?><div class="setup-success"><?= htmlspecialchars($success, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Nueva bodega</h2></header><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="create_warehouse"><label>Código<input name="code" required maxlength="40"></label><label>Nombre<input name="name" required maxlength="140"></label><label>Fundo<select name="farm_id"><option value="">Sin fundo</option><?php foreach ($farms as $farm): ?><option value="<?= (int) $farm['id'] ?>"><?= htmlspecialchars($farm['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><button class="primary-button" type="submit">Crear bodega</button></form></article><article class="admin-panel"><header class="panel-header"><h2>Nueva ubicación</h2></header><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="create_location"><label>Bodega<select name="warehouse_id" required><?php foreach ($warehouses as $warehouse): ?><option value="<?= (int) $warehouse['id'] ?>"><?= htmlspecialchars($warehouse['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Código<input name="code" required maxlength="40"></label><label>Nombre<input name="name" required maxlength="120"></label><button class="primary-button" type="submit">Crear ubicación</button></form></article><article class="admin-panel"><header class="panel-header"><h2>Nuevo lote</h2></header><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="create_lot"><label>Artículo<select name="item_id" required><?php foreach ($items as $item): ?><option value="<?= (int) $item['id'] ?>"><?= htmlspecialchars($item['name'] . ' · ' . $item['sku'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Bodega<select name="warehouse_id"><option value="">Sin bodega</option><?php foreach ($warehouses as $warehouse): ?><option value="<?= (int) $warehouse['id'] ?>"><?= htmlspecialchars($warehouse['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Número de lote<input name="lot_number" required maxlength="80"></label><label>Vencimiento<input type="date" name="expires_on"></label><label>Cantidad<input type="number" min="0" step="0.001" name="quantity" value="0" required></label><button class="primary-button" type="submit">Crear lote</button></form></article></section>
<section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Nueva transferencia</h2></header><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="create_transfer"><label>Artículo<select name="item_id" required><?php foreach ($items as $item): ?><option value="<?= (int) $item['id'] ?>"><?= htmlspecialchars($item['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Origen<select name="from_warehouse_id" required><?php foreach ($warehouses as $warehouse): ?><option value="<?= (int) $warehouse['id'] ?>"><?= htmlspecialchars($warehouse['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Destino<select name="to_warehouse_id" required><?php foreach ($warehouses as $warehouse): ?><option value="<?= (int) $warehouse['id'] ?>"><?= htmlspecialchars($warehouse['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label>Cantidad<input type="number" min="0.001" step="0.001" name="quantity" required></label><label>Fecha<input type="date" name="transfer_date" value="<?= htmlspecialchars(date('Y-m-d'), ENT_QUOTES, 'UTF-8') ?>" required></label><button class="primary-button" type="submit">Crear transferencia</button></form></article><article class="admin-panel"><header class="panel-header"><h2>Bodegas y ubicaciones</h2></header><table class="data-table"><thead><tr><th>Bodega</th><th>Código</th><th>Ubicación</th></tr></thead><tbody><?php foreach ($locations as $location): ?><tr><td><?= htmlspecialchars($location['warehouse_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($location['code'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($location['name'], ENT_QUOTES, 'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></article></section>
<section class="admin-columns"><article class="admin-panel"><header class="panel-header"><h2>Lotes</h2></header><table class="data-table"><thead><tr><th>Artículo</th><th>Lote</th><th>Vencimiento</th><th>Cantidad</th><th>Bodega</th></tr></thead><tbody><?php foreach ($lots as $lot): ?><tr><td><?= htmlspecialchars($lot['item_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($lot['lot_number'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($lot['expires_on'] ?: '—', ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string) $lot['quantity'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($lot['warehouse_name'] ?: '—', ENT_QUOTES, 'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></article><article class="admin-panel"><header class="panel-header"><h2>Transferencias</h2></header><table class="data-table"><thead><tr><th>Artículo</th><th>Origen</th><th>Destino</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach ($transfers as $transfer): ?><tr><td><?= htmlspecialchars($transfer['item_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($transfer['from_warehouse'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($transfer['to_warehouse'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($transfer['status'], ENT_QUOTES, 'UTF-8') ?></td><td><?php if ($transfer['status'] === 'DRAFT'): ?><form method="post"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="approve_transfer"><input type="hidden" name="transfer_id" value="<?= (int) $transfer['id'] ?>"><button class="button-link" type="submit">Aprobar</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></article></section>
</main></body></html>
